// Auto-generated by scripts/generate-npc-image-manifest.mjs — do not edit
const NPC_IMAGE_MANIFEST: Record<string, string> = {
  'ettercap': 'images/NPCs/ettercap.png',
  'ettercap2': 'images/NPCs/ettercap2.png',
  'flameskull': 'images/NPCs/flameskull.png',
  'giant_spider': 'images/NPCs/giant_spider.png',
  'giantspider': 'images/NPCs/giant_spider.png',
  'goblin': 'images/NPCs/goblin.png',
  'orc': 'images/NPCs/orc.png',
  'skeleton': 'images/NPCs/skeleton.png',
  'spider': 'images/NPCs/spider.png',
  'wight': 'images/NPCs/wight.png',
  'wolf_skeleton': 'images/NPCs/wolf_skeleton.png',
  'wolfskeleton': 'images/NPCs/wolf_skeleton.png',
};

export default NPC_IMAGE_MANIFEST;
